# Generated by Django 2.0.4 on 2018-07-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='continente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_continente', to='ubigeo.UbigeoContinente'),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_departamento', to='ubigeo.UbigeoDepartamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_distrito', to='ubigeo.UbigeoDistrito'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_pais', to='ubigeo.UbigeoPais'),
        ),
        migrations.AddField(
            model_name='user',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_provincia', to='ubigeo.UbigeoProvincia'),
        ),
    ]
