# Generated by Django 2.0.4 on 2018-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180721_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
