# Generated by Django 2.0.4 on 2018-07-21 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='NOmbre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='NOmbre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('tittle', models.CharField(db_index=True, max_length=250, verbose_name='Itutlo')),
                ('url_spanish', models.URLField(blank=True, null=True, verbose_name='Url pdf español')),
                ('url_quechua', models.TextField(blank=True, null=True, verbose_name='Url pdf quechua')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Article', verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='NOmbre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tittle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='NOmbre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='laws',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Tittle', verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Chapter', verbose_name='Capitulo'),
        ),
    ]
