# Generated by Django 2.0.4 on 2018-07-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Capitulo', 'verbose_name_plural': 'Capitulos'},
        ),
        migrations.AlterModelOptions(
            name='laws',
            options={'verbose_name': 'Ley', 'verbose_name_plural': 'Leyes'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='tittle',
            options={'verbose_name': 'Titulo', 'verbose_name_plural': 'Titulos'},
        ),
        migrations.AddField(
            model_name='laws',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Chapter', verbose_name='Capitulo'),
        ),
        migrations.AddField(
            model_name='laws',
            name='title_legis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Tittle', verbose_name='Titulo Legislativo'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='tittle',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Titulo de la ley'),
        ),
    ]
