# Generated by Django 2.0.4 on 2018-07-21 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legislativo', '0003_auto_20180721_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.CharField(db_index=True, max_length=250, verbose_name='Pregunta')),
                ('approved', models.BooleanField(default=False)),
                ('displeases', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Respuestas',
                'verbose_name': 'Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(verbose_name='Respuesta')),
                ('approved', models.BooleanField(default=False)),
                ('displeases', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'verbose_name': 'Pregunta',
            },
        ),
        migrations.AddField(
            model_name='laws',
            name='displeases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laws',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='law',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Laws', verbose_name='Ley'),
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='answer',
            name='law',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Laws', verbose_name='Ley'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Questions', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
