# Generated by Django 2.0.4 on 2018-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0004_auto_20180721_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
