# Generated by Django 2.0.4 on 2018-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0005_auto_20180721_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='counter',
            field=models.BooleanField(default=False),
        ),
    ]
