# Generated by Django 2.0.4 on 2018-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0006_answer_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='counter',
            field=models.BooleanField(default=False, verbose_name='Contado'),
        ),
    ]
