# Generated by Django 2.0.4 on 2018-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0007_auto_20180721_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=250, verbose_name='Codigo/Numero'),
            preserve_default=False,
        ),
    ]
