# Generated by Django 2.0.4 on 2018-07-21 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0008_laws_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='NOmbre')),
            ],
            options={
                'verbose_name_plural': 'Comision',
                'verbose_name': 'Comision',
            },
        ),
        migrations.AddField(
            model_name='laws',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de PUblicacion'),
        ),
        migrations.AddField(
            model_name='laws',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.Comision', verbose_name='Comision'),
        ),
    ]
