# Generated by Django 2.0.4 on 2018-07-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0009_auto_20180721_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='last_answer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creado'),
        ),
    ]
