# Generated by Django 2.0.4 on 2018-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0010_laws_last_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laws',
            name='last_answer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima respuesta'),
        ),
    ]
