# Generated by Django 2.0.4 on 2018-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0011_auto_20180722_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Vistas'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='Nro de Comentarios aprobados'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='displeases',
            field=models.IntegerField(default=0, verbose_name='Cantidad NO ME GUSTA'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Cantidad ME GUSTA'),
        ),
    ]
