# Generated by Django 2.0.4 on 2018-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0012_auto_20180722_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(verbose_name='Contenido de Pregunta'),
        ),
    ]
