# Generated by Django 2.0.4 on 2018-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0013_auto_20180722_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Texto de Respuesta'),
        ),
    ]
