# Generated by Django 2.0.4 on 2018-07-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0014_auto_20180722_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='law',
        ),
    ]
